#!/usr/bin/env pwsh
# Script to load secrets from Azure Key Vault for local development

Write-Host "Loading secrets from Azure Key Vault for local development..." -ForegroundColor Green

$vaultName = "secrets-3kktkazybj2b2"

# Get secrets from Key Vault
Write-Host "Retrieving AZURE_AD_CLIENT_SECRET..." -ForegroundColor Yellow
$clientSecret = az keyvault secret show --vault-name $vaultName --name "AZURE-AD-CLIENT-SECRET" --query "value" -o tsv

Write-Host "Retrieving NEXTAUTH_SECRET..." -ForegroundColor Yellow
$nextAuthSecret = az keyvault secret show --vault-name $vaultName --name "NEXTAUTH-SECRET" --query "value" -o tsv

# Create the secrets file
$secretsContent = @"
# LOCAL DEVELOPMENT SECRETS - LOADED FROM KEY VAULT
# This file is automatically generated by load-secrets.ps1

AZURE_AD_CLIENT_SECRET=$clientSecret
NEXTAUTH_SECRET=$nextAuthSecret
"@

# Ensure the file is written properly
try {
    # Remove existing file if it exists to avoid any locks
    if (Test-Path ".env.local.secrets") {
        Remove-Item ".env.local.secrets" -Force
    }
    
    # Write the content using Set-Content instead of Out-File
    Set-Content -Path ".env.local.secrets" -Value $secretsContent -Encoding UTF8 -Force
    
    # Verify the file was written
    if (Test-Path ".env.local.secrets") {
        $writtenContent = Get-Content ".env.local.secrets" -Raw
        if ($writtenContent -and $writtenContent.Contains("AZURE_AD_CLIENT_SECRET")) {
            Write-Host "✅ Secrets file written successfully" -ForegroundColor Green
        } else {
            throw "File was created but content appears incorrect"
        }
    } else {
        throw "File was not created"
    }
}
catch {
    Write-Host "❌ Failed to write secrets file: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Trying alternative method..." -ForegroundColor Yellow
    
    # Alternative method using .NET
    [System.IO.File]::WriteAllText((Join-Path $PWD ".env.local.secrets"), $secretsContent, [System.Text.Encoding]::UTF8)
    Write-Host "✅ Secrets file written using alternative method" -ForegroundColor Green
}

Write-Host "Secrets loaded successfully to .env.local.secrets" -ForegroundColor Green
Write-Host "You can now start your development server with: npm run dev" -ForegroundColor Cyan

# Note about loading the secrets file
Write-Host ""
Write-Host "IMPORTANT: Make sure to load the secrets file in your development environment:" -ForegroundColor Yellow
Write-Host "You may need to modify your package.json or use a tool like dotenv-cli" -ForegroundColor Yellow
